<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../ConsoleUtils/ConsoleUtils.csproj" />
    <ProjectReference Include="../GamesClient/GamesClient.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="States/" />
    <Folder Include="States/Game/" />
    <Folder Include="States/GameSelection/" />
  </ItemGroup>


</Project>
